name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
env:
  zig_version: 0.14.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.zig_version }}
      - run: zig build
      - run: zig build test
      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{matrix.os}}
          path: zig-out/bin/*

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.zig_version }}
      - run: zig fmt --check *.zig
