name: Build
on: [push, pull_request]
env:
  zig_version: 0.14.0 # Plug it back when the version is released

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      # Ubuntu-specific bit
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y libsdl2-dev
      - run: zig build
      - run: zig build test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check src/*.zig
